opts: !!python/object:argparse.Namespace
  CAFLOW_c_hidden_factor: 32
  UFLOW_c_hidden_factor: 64
  accelerator: null
  accumulate_grad_batches: 1
  coupling_type: Affine
  data_channels: 3
  data_dim: 2
  dataroot: caflow/datasets/celebA
  dataset_style: super-resolution
  drop_prob: 0.0
  finetuning_checkpoint: null
  finetuning_lr: 0.0001
  gamma: 0.999
  gpus: null
  gradient_clip_val: 1
  lambda_rec: null
  lamda: 0.01
  learning_rate: 0.001
  level_off_factor: 0.1
  level_off_step: 50000
  level_off_step2: 140000
  load_size: 64
  mask_to_area: 0.15
  mask_type: central
  max_dataset_size: 600
  max_steps: 200000
  model_scales: 3
  nn_type: SimpleConvNet
  no_flip: true
  num_blocks: 1
  num_channels_factor: 4
  num_components: 4
  num_nodes: 1
  num_val_samples: 6
  num_val_u_samples: 64
  preprocess:
  - resize
  pretrain: end-to-end
  r_quants: 256
  resume_from_checkpoint: null
  rflow_checkpoint: null
  rflow_scale_depth: 2
  s_cond_s_scale_depth: 12
  s_cond_u_scale_depth: 16
  sample_norm_range: !!python/tuple
  - 0
  - 255
  sample_normalize: true
  sample_pad_value: 0
  sample_padding: 2
  sample_scale_each: false
  sampling_temperatures:
  - 1
  - 0.9
  - 0.8
  shared: false
  sr_factor: 8
  t_quants: 256
  tflow_checkpoint: null
  tflow_scale_depth: 4
  train_batch: 1
  train_shortcut: true
  train_workers: 4
  u_cond_scale_depth: 4
  use_attn: false
  use_ema: true
  use_warm_up: true
  val_batch: 1
  val_shortcut: true
  val_workers: 4
  vardeq_depth: 0
  warm_up: 500
